apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tekton-ws-pr-
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  params:
    - name: gitAppUrl
      value: https://github.com/kosilva93/enghouse-demo.git
    - name: gitRevision
      value: main
    - name: GOALS	
      value: ["-DskipTests","clean","install"]
    - name: pathToYamlFile
      value: "kubernetes/springdemo.yaml"
    - name: imageUrl
      value: us.icr.io/kos-demo-enghouse/demo-enghouse
    - name: imageTag
      value: "v1"
  serviceAccountName: pipeline
  workspaces:
    - name: git-source
      persistentVolumeClaim:
        claimName: tekton-ws-pvc
